includes:
- ../mmf-hateful-memes/projects/visual_bert/configs/hateful_memes/from_coco.yaml

env:
  save_dir: save
  data_dir: datasets

dataset_config:
  hateful_memes:
    data_dir: datasets
    features:
      train: features/detectron.lmdb
      val: features/detectron.lmdb
      test: features/detectron.lmdb
    annotations:
      train: annotations/train_objects_back_translation.jsonl
      val: annotations/dev_unseen_objects.jsonl
      test: annotations/test_seen_objects.jsonl
    max_features: 36
    processors:
      text_processor:
        params:
          max_length: 64
          max_seq_length: 96

training:
  seed: 1234
  batch_size: 32
  max_updates: 10000
  checkpoint_interval: 500
  evaluation_interval: 500