includes:
- ../mmf-hateful-memes/projects/visual_bert/configs/hateful_memes/from_coco.yaml

env:
  save_dir: save
  data_dir: datasets

dataset_config:
  hateful_memes:
    data_dir: datasets
    features:
      train: features/train.lmdb
      val: features/dev.lmdb
      test: features/test.lmdb
    annotations:
      train: annotations/train.jsonl
      val: annotations/dev_unseen.jsonl
      test: annotations/test_unseen.jsonl
    processors.text_processor.params.max_seq_length: 96

training:
  batch_size: 8
  max_updates: 10000
  checkpoint_interval: 500
  evaluation_interval: 500