includes:
- ../mmf-hateful-memes/projects/visual_bert/configs/hateful_memes/from_coco.yaml

env:
  save_dir: ./save
  log_dir: ./logs

dataset_config:
  hateful_memes:
    data_dir: datasets
    features:
      train: features/detectron.lmdb
      val: features/detectron.lmdb
      test: features/detectron.lmdb
    annotations:
      train: annotations/train.jsonl
      val: annotations/dev_unseen.jsonl
      test: annotations/test_unseen.jsonl
    max_features: 36
    processors:
      text_processor:
        params:
          max_length: 32
          max_seq_length: 64

training:
  batch_size: 32
  max_updates: 10000
  checkpoint_interval: 500
  evaluation_interval: 500